-- No-op migration.
--
-- This migration previously dropped Embedding.vector and related indexes, which
-- breaks semantic search and conflicts with the current schema.
-- Keep this migration as an empty checkpoint so migration history remains linear.
